//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGTFIMUNCP.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.Documento = new HashSet<Documento>();
            this.PlanTesis = new HashSet<PlanTesis>();
        }
    
        public int idSolicitud { get; set; }
        public string asuntoSolicitud { get; set; }
        public string numRegSolicitud { get; set; }
        public System.DateTime fechaRecSolicitud { get; set; }
        public string obsSolicitud { get; set; }
        public string reqSolicitud { get; set; }
        public bool validacionReqSolicitud { get; set; }
        public bool estadoSolicitud { get; set; }
        public string atencionSolicitud { get; set; }
        public int idReqProc { get; set; }
        public int idEgresado { get; set; }
        public int idUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual Egresado Egresado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanTesis> PlanTesis { get; set; }
        public virtual Requisito_procedimiento Requisito_procedimiento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
