//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGTFIMUNCP.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaGTFIMUNCPEntities : DbContext
    {
        public SistemaGTFIMUNCPEntities()
            : base("name=SistemaGTFIMUNCPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Documento> Documentos { get; set; }
        public virtual DbSet<Egresado> Egresados { get; set; }
        public virtual DbSet<Facultad> Facultades { get; set; }
        public virtual DbSet<PlanTesis> PlanTesis { get; set; }
        public virtual DbSet<Procedimiento> Procedimientos { get; set; }
        public virtual DbSet<Requisito> Requisitos { get; set; }
        public virtual DbSet<Requisito_procedimiento> Requisitos_procedimiento { get; set; }
        public virtual DbSet<Responsable> Responsables { get; set; }
        public virtual DbSet<Rol> Roles { get; set; }
        public virtual DbSet<Solicitud> Solicitudes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
